// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"google.golang.org/protobuf/types/known/timestamppb"
)

type User struct {
	ID              string                 `json:"id"`
	Name            string                 `json:"name"`
	Email           string                 `json:"email"`
	Password        string                 `json:"password"`
	TelephoneNumber string                 `json:"telephoneNumber"`
	Gender          int64                  `json:"gender"`
	CreatedAt       *timestamppb.Timestamp `json:"createdAt"`
	UpdatedAt       *timestamppb.Timestamp `json:"updatedAt"`
}

type GetUserByIDRequest struct {
	ID string `json:"id"`
}

type GetUserByIDResponse struct {
	User *User `json:"user"`
}
