// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"google.golang.org/protobuf/types/known/timestamppb"
)

type CreateUserRequest struct {
	Name            string `json:"name"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	TelephoneNumber string `json:"telephoneNumber"`
	Gender          int64  `json:"gender"`
}

type CreateUserResponse struct {
	UUID      string     `json:"uuid"`
	TokenPair *TokenPair `json:"tokenPair"`
}

type DeleteUserRequest struct {
	UUID string `json:"uuid"`
}

type DeleteUserResponse struct {
	UUID string `json:"uuid"`
}

type TokenPair struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type UpdateUserRequest struct {
	UUID            string `json:"uuid"`
	Name            string `json:"name"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	TelephoneNumber string `json:"telephoneNumber"`
	Gender          int64  `json:"gender"`
}

type UpdateUserResponse struct {
	UUID      string     `json:"uuid"`
	TokenPair *TokenPair `json:"tokenPair"`
}

type User struct {
	UUID            string                 `json:"uuid"`
	Name            string                 `json:"name"`
	Email           string                 `json:"email"`
	Password        string                 `json:"password"`
	TelephoneNumber string                 `json:"telephoneNumber"`
	Gender          int64                  `json:"gender"`
	CreatedAt       *timestamppb.Timestamp `json:"createdAt"`
	UpdatedAt       *timestamppb.Timestamp `json:"updatedAt"`
}

type GetUserByIDRequest struct {
	UUID string `json:"uuid"`
}

type GetUserByIDResponse struct {
	User *User `json:"user"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	TokenPair *TokenPair `json:"tokenPair"`
}
